# Generated by Django 5.2 on 2025-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('wheelchairAccessible', models.BooleanField()),
                ('changingTable', models.BooleanField()),
                ('freetoUse', models.BooleanField()),
                ('openNow', models.BooleanField()),
                ('accessibility', models.CharField(choices=[('accessible', 'Accessible'), ('not accessible', 'Not accessible')], max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('distanceValue', models.FloatField()),
                ('openingHours', models.JSONField()),
            ],
        ),
    ]
